version: "3.9"

services:
  odoo:
    image: ghcr.io/odoonix/openpos:18.0
    container_name: odoo
    depends_on:
      - db

    environment:
      DB_PORT_5432_TCP_ADDR: ${DB_PORT_5432_TCP_ADDR}
      DB_PORT_5432_TCP_PORT: ${DB_PORT_5432_TCP_PORT}
      DB_ENV_POSTGRES_USER: ${DB_ENV_POSTGRES_USER}
      DB_ENV_POSTGRES_PASSWORD: ${DB_ENV_POSTGRES_PASSWORD}
      DB_ENV_NAME: ${DB_ENV_NAME}

      ODOO_INIT_MODULES: point_of_sale,connector,account,web_responsive

    volumes:
      - ./odoo/data:/var/lib/odoo-data

  db:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data


  cups:
    image: ghcr.io/odoonix/cups-epos-web
    container_name: cups

    environment:
      PRINT_LOG: ${PRINT_LOG}
      PRINT_TEMP_DIR: ${PRINT_TEMP_DIR}

    volumes:
      - ./cups/printer_output:/printer_output
      - ./cups/etc:/etc/cups
      - ./cups/spool:/var/spool/cups

  nginx:
    build: ./nginx
    container_name: odoo-nginx
    depends_on:
      - odoo
      - db
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "361:361"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/generate-cert.sh:/docker-entrypoint.d/10-generate-cert.sh

